Resources:
  myDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: reservations
      AttributeDefinitions:
        - AttributeName: "ownerId"
          AttributeType: "S"
        - AttributeName: "reservationId"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "ownerId"
          KeyType: "HASH"
        - AttributeName: "reservationId"
          KeyType: "RANGE"
      BillingMode: PAY_PER_REQUEST